import { StyleSheet } from "react-native"
import { responsive, spacing } from "./global"

export const getHintStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      alignItems: "center",
      justifyContent: "center",
      marginVertical: responsive.scale(2),
      width: "100%",
    },
    hintButtonsContainer: {
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
      overflow: "hidden",
    },
    hintLabel: {
      color: colors.textSecondary,
      fontFamily: "Arvo-Bold",
      fontSize: responsive.responsiveFontSize(14),
      marginVertical: responsive.scale(4),
      textAlign: "center",
      width: "100%",
      paddingVertical: responsive.scale(4),
    },
    hintLabelDisabled: {
      color: colors.textDisabled,
      fontFamily: "Arvo-Italic",
      fontSize: responsive.responsiveFontSize(14),
      marginVertical: responsive.scale(4),
      textAlign: "center",
      width: "100%",
      paddingVertical: responsive.scale(4),
    },
    skeletonLabel: {
      backgroundColor: colors.surface,
      height: responsive.scale(20),
      width: "50%",
      borderRadius: responsive.scale(4),
      marginVertical: responsive.scale(10),
    },
    hintButtonArea: {
      flexDirection: "row",
      justifyContent: "center",
      flexWrap: "nowrap",
      width: "100%",
    },
    hintButton: {
      borderRadius: responsive.scale(4),
      padding: responsive.scale(6),
      minWidth: "20%",
      alignItems: "center",
      justifyContent: "center",
      marginHorizontal: responsive.scale(4),
      marginVertical: responsive.scale(8),
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: colors.textSecondary,
    },
    usedHintButton: {
      backgroundColor: "transparent",
      opacity: 0.8,
      borderColor: colors.tertiary,
    },
    highlightedHintButton: {
      borderColor: colors.primary,
      borderWidth: 2,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.8,
      shadowRadius: 5,
      elevation: 5,
    },
    buttonText: {
      color: colors.textPrimary,
      fontSize: responsive.responsiveFontSize(14),
      textAlign: "center",
      marginTop: responsive.scale(4),
    },
    disabled: {
      opacity: 0.5,
    },
    buttonTextSmall: {
      color: colors.textSecondary,
      fontFamily: "Arvo-Regular",
      fontSize: responsive.responsiveFontSize(12),
      marginTop: responsive.scale(4),
      textAlign: "center",
    },
    displayedHintContainer: {
      marginTop: responsive.scale(12),
      paddingVertical: responsive.scale(10),
      paddingHorizontal: responsive.scale(16),
      backgroundColor: colors.surface,
      borderRadius: responsive.scale(8),
      width: "90%",
      alignSelf: "center",
    },
    hintText: {
      color: colors.primary,
      fontFamily: "Arvo-Bold",
      fontSize: responsive.responsiveFontSize(16),
      textAlign: "center",
    },
    veryEasyContainer: {
      width: "90%",
      backgroundColor: colors.surface,
      borderRadius: responsive.scale(8),
      padding: spacing.medium,
      marginVertical: spacing.small,
    },
    veryEasyTitle: {
      fontFamily: "Arvo-Bold",
      fontSize: responsive.responsiveFontSize(16),
      color: colors.primary,
      textAlign: "center",
      marginBottom: spacing.small,
    },
    veryEasyText: {
      fontFamily: "Arvo-Regular",
      fontSize: responsive.responsiveFontSize(14),
      color: colors.textSecondary,
      lineHeight: responsive.responsiveFontSize(20),
    },
    veryEasyHintLabel: {
      fontFamily: "Arvo-Bold",
      color: colors.textPrimary,
    },
  })
