import { StyleSheet } from "react-native"
import { colors, responsive } from "./global"

export const pickerStyles = StyleSheet.create({
  activityIndicator: {
    position: "absolute",
    right: responsive.scale(10),
    top: responsive.scale(6),
  },
  button: {
    backgroundColor: "transparent",
    borderRadius: responsive.scale(10),
    paddingVertical: responsive.scale(12),
    paddingHorizontal: responsive.scale(15),
    width: "100%",
    height: "auto",
    elevation: 0,
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    boxShadow: "none",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.primary,
  },
  buttonSmall: {
    minHeight: responsive.scale(55),
  },
  buttonText: {
    color: colors.secondary,
    fontFamily: "Arvo-Regular",
    fontSize: responsive.responsiveFontSize(18),
    textAlign: "center",
    paddingVertical: responsive.scale(4),
  },
  buttonTextSmall: {
    fontSize: responsive.responsiveFontSize(14),
  },
  container: {
    flex: 1,
    minHeight: responsive.scale(180),
    maxWidth: responsive.scale(400),
    width: "100%",
    alignSelf: "center",
    marginBottom: responsive.scale(15),
  },
  input: {
    alignSelf: "flex-start",
    borderColor: colors.lightGrey,
    borderRadius: responsive.scale(8),
    borderWidth: 2,
    color: colors.secondary,
    fontFamily: "Arvo-Regular",
    padding: responsive.scale(10),
    textAlign: "left",
    width: "100%",
    marginBottom: responsive.scale(12),
    maxWidth: responsive.scale(400),
    fontSize: responsive.responsiveFontSize(16),
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginBottom: responsive.scale(8),
    position: "relative",
  },
  pressableText: {
    flex: 1,
    fontFamily: "Arvo-Regular",
    padding: responsive.scale(8),
    borderRadius: responsive.scale(5),
  },
  searchIndicator: {
    marginLeft: responsive.scale(-25),
  },
  selectedMovie: {
    backgroundColor: colors.grey,
  },
  resultsContainer: {
    marginBottom: responsive.scale(10),
    maxHeight: responsive.scale(100),
    minHeight: responsive.scale(82),
    maxWidth: responsive.scale(400),
    width: "100%",
  },
  resultsShow: {
    flex: 1,
  },
  text: {
    fontFamily: "Arvo-Regular",
    fontSize: responsive.responsiveFontSize(12),
    padding: responsive.scale(10),
    lineHeight: responsive.responsiveFontSize(16),
    marginBottom: responsive.scale(10),
  },
  noResultsText: {
    fontFamily: "Arvo-Regular",
    fontSize: responsive.responsiveFontSize(16),
    color: colors.lightGrey,
    textAlign: "center",
    padding: responsive.scale(10),
  },
  errorText: {
    fontFamily: "Arvo-Regular",
    fontSize: responsive.responsiveFontSize(14),
    color: colors.quaternary,
    textAlign: "center",
    padding: responsive.scale(10),
  },
  unselected: {
    color: colors.lightGrey,
    fontFamily: "Arvo-Italic",
    fontSize: responsive.responsiveFontSize(16),
  },
  disabledButton: {
    backgroundColor: "transparent",
    opacity: 0.5,
    borderColor: colors.tertiary,
  },
})
