import React, { ReactElement } from "react"
import { render, screen, RenderOptions } from "@testing-library/react-native"
import { ThemeProvider } from "../src/contexts/themeContext"
import WhereToWatch from "../src/components/whereToWatch"

// --- Mocks ---
// Override the global vector-icons mock to include FontAwesome5
jest.mock("@expo/vector-icons", () => {
  const { Text } = require("react-native")
  const MockIcon = ({ name, ...props }: any) => (
    <Text testID={`mock-icon-${name}`} {...props}>
      {name}
    </Text>
  )
  return {
    FontAwesome5: MockIcon,
  }
})

// --- Test Setup ---
const renderWithTheme = (ui: ReactElement, options?: RenderOptions) => {
  return render(<ThemeProvider>{ui}</ThemeProvider>, options)
}

describe("WhereToWatch Component", () => {
  it("should render the title", () => {
    renderWithTheme(<WhereToWatch />)
    expect(screen.getByText("Where to Watch")).toBeTruthy()
  })

  it("should render the streaming provider icons/labels", () => {
    renderWithTheme(<WhereToWatch />)

    // We check for the text labels of the providers
    expect(screen.getByText("Netflix")).toBeTruthy()
    expect(screen.getByText("Prime Video")).toBeTruthy()
    expect(screen.getByText("Disney+")).toBeTruthy()
    expect(screen.getByText("Rent")).toBeTruthy()
  })

  it("should render the disclaimer text", () => {
    renderWithTheme(<WhereToWatch />)

    expect(
      screen.getByText(
        "*Streaming availability is illustrative and may change."
      )
    ).toBeTruthy()
  })

  it("should verify icons are rendered", () => {
    renderWithTheme(<WhereToWatch />)

    // Verify the testIDs generated by our local mock
    expect(screen.getByTestId("mock-icon-netflix")).toBeTruthy()
    expect(screen.getByTestId("mock-icon-amazon")).toBeTruthy()
    expect(screen.getByTestId("mock-icon-plus")).toBeTruthy()
    expect(screen.getByTestId("mock-icon-ticket-alt")).toBeTruthy()
  })
})
